{
 "title": "wis2box data publication dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Current Alerts Overview", "type": "alertlist", "description": "show all the alerting list", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Station data publishing status",
   "type": "table",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg by(WSI) (wis2box_stations_wsi{WSI!=\"none\"})"
    },
    {
     "expr": "sum by(WSI, description) (increase(wis2box_failure_descr_wsi_total{WSI!=\"none\"}[$__interval]))"
    },
    {
     "expr": "sum by(WSI) (increase(wis2box_notify_wsi_total{WSI!=\"none\"}[$__interval]))"
    },
    {
     "expr": "sum by(WSI) (increase(wis2box_failure_wsi_total{WSI!=\"none\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New/updated files in wis2box-incoming storage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 3 },
   "targets": [
    {
     "expr": "delta(wis2box_storage_incoming_total{}[$__interval])",
     "legendFormat": "New/updated files per hour in wis2box-incoming"
    }
   ]
  },
  {
   "title": "New/updated files in wis2box-public storage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "delta(wis2box_storage_public_total{}[$__interval])",
     "legendFormat": "New/updated files in wis2box-public"
    }
   ]
  },
  {
   "title": "Number of WIS2.0 notifications published by wis2box",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "delta(wis2box_notify_total[$__interval])",
     "legendFormat": "WIS2.0 notifications"
    }
   ]
  },
  {
   "title": "wis2box ERRORs and WARNINGs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{compose_service=\"wis2box-management\"} |~ `ERROR`"
    },
    {
     "expr": "{compose_service=\"wis2box-management\"} |= `wis2box` |= `WARNING`"
    },
    {
     "expr": "{compose_service=\"wis2box-api\"} |= `wis2box_api` |= `ERROR`"
    },
    {
     "expr": "{compose_service=\"wis2box-api\"} |= `wis2box_api` |= `WARNING` "
    },
    {
     "direction": "backward",
     "expr": "{container_name=\"wis2box-api\"} |= `ECCODES ERROR`"
    }
   ]
  }
 ]
}