{
 "title": "alarmtracking dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes / node_filesystem_size_bytes) * 100",
     "legendFormat": "Disk Usage (%)"
    }
   ]
  },
  {
   "title": "Count of indices that have read_only_allow_delete=true",
   "type": "timeseries",
   "description": "metrics: elasticsearch_indices_settings_stats_read_only_indices",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_indices_settings_stats_read_only_indices[$__rate_interval]))",
     "legendFormat": "Count of indices that have read_only_allow_delete=true"
    }
   ]
  },
  {
   "title": "Free space on block device in bytes",
   "type": "gauge",
   "description": "Metric: elasticsearch_filesystem_data_free_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_filesystem_data_free_bytes{cluster=\"es-wis2box\"})",
     "legendFormat": "Free space on block device in bytes"
    }
   ]
  },
  {
   "title": "Available space on block device in bytes",
   "type": "gauge",
   "description": "Metric: elasticsearch_filesystem_data_available_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_filesystem_data_available_bytes{cluster=\"es-wis2box\"})",
     "legendFormat": "Available space on block device in bytes"
    }
   ]
  }
 ]
}