{
 "title": "Storage statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total objects stored per bucket",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_bucket_usage_object_total",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total MB stored per bucket",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minio_bucket_usage_total_bytes", "legendFormat": "{{bucket}}" }
   ]
  },
  {
   "title": "Traffic sent bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(minio_bucket_traffic_sent_bytes[$__rate_interval])",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Traffic received bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(minio_bucket_traffic_received_bytes[$__rate_interval])",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}