{
 "title": "wis2-downloader monitoring dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "WIS2-downloader subscriptions",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(topic) (topic_subscription_status == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download queue size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "queue_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Files downloaded last hour",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(downloaded_files_total[1h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Data downloaded last hour",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(downloaded_bytes_total[1h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Files downloaded by file-type",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(downloaded_files_total{file_type=\"bufr\"}[1h]))",
     "legendFormat": "BUFR"
    },
    {
     "expr": "sum(increase(downloaded_files_total{file_type=\"grib\"}[1h]))",
     "legendFormat": "GRIB"
    },
    {
     "expr": "sum(increase(downloaded_files_total{file_type!~\"bufr|grib\"}[1h]))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Data downloaded by file-type",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(downloaded_bytes_total{file_type=\"bufr\"}[1h]))",
     "legendFormat": "BUFR"
    },
    {
     "expr": "sum(increase(downloaded_bytes_total{file_type=\"grib\"}[1h]))",
     "legendFormat": "GRIB"
    },
    {
     "expr": "sum(increase(downloaded_bytes_total{file_type!~\"grib|bufr\"}[1h]))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Data downloaded per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(downloaded_bytes_total[1m]))",
     "legendFormat": "Data downloaded per minute"
    }
   ]
  },
  {
   "title": "WIS2 downloader logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "{container_name=\"wis2-downloader\"} != `Queue` != `GET` != `CLEAN`"
    }
   ]
  },
  {
   "title": "Files downloaded per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(downloaded_files_total[1m]))",
     "legendFormat": "Files downloaded per minute"
    }
   ]
  }
 ]
}