{
 "title": "wis2box broker statistics $SYS/broker/messages",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "wis2box-broker: messages sent",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "wis2box_broker_msg_sent", "legendFormat": "messages sent" }
   ]
  },
  {
   "title": "wis2box-broker: messages dropped",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 0 },
   "targets": [
    { "expr": "wis2box_broker_msg_dropped", "legendFormat": "messages dropped" }
   ]
  },
  {
   "title": "wis2box-broker: messages received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "targets": [
    { "expr": "wis2box_broker_msg_received", "legendFormat": "messages received" }
   ]
  },
  {
   "title": "wis2box-broker: messages stored",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 11 },
   "targets": [
    { "expr": "wis2box_broker_msg_stored", "legendFormat": "messages stored" }
   ]
  }
 ]
}