{
 "title": "wis2downloader dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "WIS2-downloader subscriptions",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(topic) (topic_subscription_status == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download queue size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "queue_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Files downloaded by file-type, last hour",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(downloaded_files_total{file_type=\"bufr\"} or vector(0))[1h:])",
     "legendFormat": "BUFR"
    },
    {
     "expr": "increase(sum(downloaded_files_total{file_type=\"grib\"} or vector(0))[1h:])",
     "legendFormat": "GRIB"
    },
    {
     "expr": "increase(sum(downloaded_files_total{file_type!~\"bufr|grib\"} or vector(0))[1h:])",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Data downloaded by file-type, last hour",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(downloaded_bytes_total{file_type=\"bufr\"} or vector(0))[1h:])",
     "legendFormat": "BUFR"
    },
    {
     "expr": "increase(sum(downloaded_bytes_total{file_type=\"grib\"} or vector(0))[1h:])",
     "legendFormat": "GRIB"
    },
    {
     "expr": "increase(sum(downloaded_bytes_total{file_type!~\"grib|bufr\"} or vector(0))[1h:])",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Successful / Failed downloads per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 4 },
   "targets": [
    {
     "expr": "increase(sum(downloaded_files_total or vector(0))[1m:])",
     "legendFormat": "Successful downloads per minute"
    },
    {
     "expr": "increase(sum(failed_downloads_total or vector(0))[1m:])",
     "legendFormat": "Failed downloads per minute"
    }
   ]
  },
  {
   "title": "WIS2 downloader logs: ERROR and WARNING",
   "type": "logs",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{container_name=\"wis2downloader\"} != `Queue` != `GET` != `CLEAN` |~ `ERROR|WARNING`"
    }
   ]
  },
  {
   "title": "Data downloaded per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(sum(downloaded_bytes_total or vector(0))[1m:])",
     "legendFormat": "Data downloaded per minute"
    }
   ]
  }
 ]
}