{
 "title": "Subscribe & Publish Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "de-republisher activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({compose_service=\"de-republisher\"} |= \"INFO\" [1m]))",
     "legendFormat": "Number of INFOs"
    },
    {
     "expr": "sum(count_over_time({compose_service=\"de-republisher\"} |= \"WARNING\" [1m]))",
     "legendFormat": "Number of WARNINGs"
    },
    {
     "expr": "sum(count_over_time({compose_service=\"de-republisher\"} |= \"ERROR\" [1m]))",
     "legendFormat": "Number of ERRORs",
     "resolution": 1
    }
   ]
  },
  {
   "title": "mqp-publisher activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({compose_service=\"mqp-publisher\"} |= \"INFO\" [1m]))",
     "legendFormat": "Number of INFOs"
    },
    {
     "expr": "sum(count_over_time({compose_service=\"mqp-publisher\"} |= \"WARNING\" [1m]))",
     "legendFormat": "Number of WARNINGs"
    },
    {
     "expr": "sum(count_over_time({compose_service=\"mqp-publisher\"} |= \"ERROR\" [1m]))",
     "legendFormat": "Number of ERRORs",
     "resolution": 1
    }
   ]
  },
  {
   "title": "de-republisher logs, ERROR",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{compose_service=\"de-republisher\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "mqp-publisher logs, ERROR",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{compose_service=\"mqp-publisher\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "de-republisher logs, WARNING",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{compose_service=\"de-republisher\"} |= \"WARNING\""
    }
   ]
  },
  {
   "title": "mqp-publisher logs, WARNING",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "{compose_service=\"mqp-publisher\"} |= \"WARNING\""
    }
   ]
  },
  {
   "title": "de-republisher logs, INFO",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{compose_service=\"de-republisher\"} |= \"INFO\""
    }
   ]
  },
  {
   "title": "mqp-publisher logs, INFO",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{compose_service=\"mqp-publisher\"} |= \"INFO\""
    }
   ]
  }
 ]
}